### ISSUE TITLE
Missing R_logo_pattern.pdf

### ISSUE THREAD

**Issue by mustberuss** [awalsh17/quiltR#1]
https://github.com/awalsh17/quiltR/blob/9fe9176fd57e8e3c526108cd6d7bd155fd1dfb0d/README.md?plain=1#L60-L62

The pattern link is a 404.  Really just an excuse to say your RStudio::conf talk was awesome!  Especially liked your "idea quota".

**Comment by awalsh17** [comment]
Thanks! Added the pattern!
https://github.com/awalsh17/quiltR/commit/d00cb9f1a6aa484f02efa28ba3b12f2b29f2f7d1
